[[QD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "28ff497ec71c9bbcfeded0eaab52fb9871600da3"
libc = "musl"
os = "linux"

    [[QD.download]]
    sha256 = "bec62fb8b40fdc3eaeaaab3a013541a05114d8c12093dd207196dd5c48456eec"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.aarch64-linux-musl-cxx03.tar.gz"
[[QD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9eedf285d2465b601959be5fcbd75ef6071fa41"
libc = "musl"
os = "linux"

    [[QD.download]]
    sha256 = "65f9c02f5654230a163da6ca12b5b75b628ddb31cd3813930075319a58436ff4"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.aarch64-linux-musl-cxx11.tar.gz"
[[QD]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7904fb40e7f25ea8f6659c36a2334852ec1d4cab"
libc = "musl"
os = "linux"

    [[QD.download]]
    sha256 = "98fedf2f5149a042ee5227449101dcfbd2b915923cac634f5c140a7f10e7a8ee"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.armv7l-linux-musleabihf-cxx03.tar.gz"
[[QD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "378287727183b3df0fc9891a802c81a635a3be15"
libc = "musl"
os = "linux"

    [[QD.download]]
    sha256 = "1b86cdf8d3acfa54f6086c5b544cf5ea5b2ff9f2235df7885fd6fdc94adfecae"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.i686-linux-musl-cxx11.tar.gz"
[[QD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "104a74609f032e4d1e722d03bcf689923ac9eaad"
libc = "musl"
os = "linux"

    [[QD.download]]
    sha256 = "6f7cd62ba54b175b252f2c1f2cfb8fb62bc229d4717d4e84bbf986fedd9058b6"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.x86_64-linux-musl-cxx11.tar.gz"
[[QD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f3bf9917275675cec9e51a9b2dac4c03cc4b1dd"
libc = "glibc"
os = "linux"

    [[QD.download]]
    sha256 = "5ae2933ead83463c44f8d335caead8107c8e0cd5c105370c847e60ac16ff85d1"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.x86_64-linux-gnu-cxx03.tar.gz"
[[QD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "571359afbd5c9c77a9ddf5325f1f2e860b45a70f"
libc = "glibc"
os = "linux"

    [[QD.download]]
    sha256 = "cfe5cd93cd1432c91e6854d4b4f9de08eee4f040c568987845df3e9b3573a120"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.i686-linux-gnu-cxx03.tar.gz"
[[QD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bed5441e2ce2c03fbc9958a27227a2d0de9a2d7"
os = "macos"

    [[QD.download]]
    sha256 = "326974ef464c7e8589d7dec49b30cfb6875d2bbc9c36b498e6bfe9308cb7fb26"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.x86_64-apple-darwin14-cxx11.tar.gz"
[[QD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fc200621882cc0371a8538e28b676a41a70258f"
libc = "glibc"
os = "linux"

    [[QD.download]]
    sha256 = "02f50ceba2bb8b26b856d64206a3e6cdf83768130ad72da0a16b6ab74463fbfd"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.i686-linux-gnu-cxx11.tar.gz"
[[QD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e37ddbeb239f39d492e1eab1ddaf7c43b39ff59"
libc = "glibc"
os = "linux"

    [[QD.download]]
    sha256 = "ac2996d8fe4219ede77d528401d4dd579d29733f6cce5a238e638a3688c2c325"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.x86_64-linux-gnu-cxx11.tar.gz"
[[QD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba237e595749fb2e6722737ee4ef1bb83b954324"
libc = "glibc"
os = "linux"

    [[QD.download]]
    sha256 = "d4516e9d76027f54db0193b301efc97769a8e69fb608c70b026c9464a4470706"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.powerpc64le-linux-gnu-cxx11.tar.gz"
[[QD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7cd4aa9fda77080e8f90e8601538be84868609e0"
libc = "glibc"
os = "linux"

    [[QD.download]]
    sha256 = "286b1320c5caa47a2b3f7a7a75c72c8fe3b39989971ddde214ee04d86011c341"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.aarch64-linux-gnu-cxx11.tar.gz"
[[QD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91dd4d48e4dffec892c9b11572830bb49fae571a"
libc = "musl"
os = "linux"

    [[QD.download]]
    sha256 = "7cd22785d183280199529727dced1be6d1d9f9c5eaf5ba56d8095be21f6911a4"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.x86_64-linux-musl-cxx03.tar.gz"
[[QD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4af72117170a4b48e112b80896928746371fccc4"
os = "macos"

    [[QD.download]]
    sha256 = "102070322e250d8395eb464e917039b81e8378b79e5b0a6e6b6ff84c6f004f51"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.x86_64-apple-darwin14-cxx03.tar.gz"
[[QD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6bb797da7437e10d35f9da38722e84641bb104df"
os = "freebsd"

    [[QD.download]]
    sha256 = "57dc2b63dcb11ab7f73c818fe4f9aa155d815d8f973c7c4b5939e98c033d416b"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[QD]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a26005301e02268472272bd71a6d37581a97a65d"
libc = "glibc"
os = "linux"

    [[QD.download]]
    sha256 = "b9c834fadfab2b1884740079de83750607835109650b4af794e6063d9fc4cb3a"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.powerpc64le-linux-gnu-cxx03.tar.gz"
[[QD]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45a36c0180a6cad98efd4aafdb460bb6843f98f9"
libc = "musl"
os = "linux"

    [[QD.download]]
    sha256 = "d8121e294c0d143515926bc4b1ab0951e4b1c5ceb77a751ec9e32410276a88f2"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.armv7l-linux-musleabihf-cxx11.tar.gz"
[[QD]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df05bb92848b287bfc322b663c3be42d85f8369a"
libc = "glibc"
os = "linux"

    [[QD.download]]
    sha256 = "007fe4832113478c539248ae4d93bc215f64d55045903d2b51f854bd2c995398"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[QD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "032eb2aa96122a2a343a6a84b0d0648049522214"
libc = "glibc"
os = "linux"

    [[QD.download]]
    sha256 = "74088b8c2cb4b28540258f9f7b08728dcfefa101b0337560cfddeab7011903c6"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.aarch64-linux-gnu-cxx03.tar.gz"
[[QD]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "354813490e097e6c01c91d08ea3005f37a155bde"
libc = "glibc"
os = "linux"

    [[QD.download]]
    sha256 = "387ca3341c218af12f1bbea40c6b25ebb18ef03f2d97c6960aea534cb38d68c6"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[QD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c2857b75e24c9df002360badc3a31ac71e94fdc"
os = "freebsd"

    [[QD.download]]
    sha256 = "6edb2cdbb598be2af1eccebafe8af6ab1f8b489037b50e1cc8f32f7341b5ec19"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[QD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38fe6c27ebaccf23f7082262702798c5c53a9a1c"
libc = "musl"
os = "linux"

    [[QD.download]]
    sha256 = "e142e9b9af142381bd5b1498ea2dd812c036fca80d01ffcb50c9ff25ea571e6b"
    url = "https://github.com/JuliaBinaryWrappers/QD_jll.jl/releases/download/QD-v2.3.22+1/QD.v2.3.22.i686-linux-musl-cxx03.tar.gz"
